### ISSUE TITLE
Install Fluent on Ubuntu 16.04/18.04?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fluent-adapter#3]
Officially, only the Linux distributions *CentOS* and *Red Hat Linux* are supported. However, for development it would be convenient to be able to use Fluent on Ubuntu 16.04/18.04.

In this issue we want to answer the following questions:

- [x] Is it possible to install Fluent 19.01 on Ubuntu 16.04? 
- [x] If yes, how? See https://github.com/precice/fluent-adapter/issues/3#issuecomment-447482170
- [x] ~~Is it possible to install Fluent 19.01 on Ubuntu 18.04?~~ no
- [x] ~~If yes, how?~~ no
- [x] Is it possible to install Fluent 19.02 on Ubuntu 18.04? postponed for now, but should be working due to [this post](https://www.cfd-online.com/Forums/ansys/203041-installation-ansys-19-ubuntu-18-4-a.html#6) on CFD Online. ANSYS Fluent R3 19.05 works successfully on Ubuntu 18.04 

In the end we should verify our installation by running a small test case. For example the [lid driven cavity](https://www.youtube.com/watch?v=2u1j0b5nKwA).

**Comment by lixiaole2017** [comment]
I've installed fluent18.2.0 in CentOS 7.

**Comment by IshaanDesai** [comment]
FLUENT on ANSYS 19.1 is successfully installed on Linux Ubuntu 16.04 using the installation guide: https://www.cfd-online.com/Forums/ansys/199190-ansys-18-2-ubuntu-16-04-installation-guide.html 

Following the same installation guide for Linux Ubuntu 18.04 leads to installation hang at 89 or 90%. Last entry in `install.log` is:
```
AWPROOTDIR = /home/ishaan/ansys_inc/v191
Creating ANSYS RSM Cluster Node Service script ...
Created service script: arcnode
```

**Comment by jingchangshi** [comment]
> FLUENT on ANSYS 19.1 is successfully installed on Linux Ubuntu 16.04 using the installation guide: https://www.cfd-online.com/Forums/ansys/199190-ansys-18-2-ubuntu-16-04-installation-guide.html
> 
> Following the same installation guide for Linux Ubuntu 18.04 leads to installation hang at 89 or 90%. Last entry in `install.log` is:
> 
> ```
> AWPROOTDIR = /home/ishaan/ansys_inc/v191
> Creating ANSYS RSM Cluster Node Service script ...
> Created service script: arcnode
> ```

In fact, this is not critical. You can just ignore it and close the installation GUI. Then kill all ansys related processes. The critical thing should be the ownership of the directory $HOME/.ansys. The installation is by sudo or root while the execution is by a regular user. That is the problem. At least for me, this solution works.

**Comment by IshaanDesai** [comment]
> 
> In fact, this is not critical. You can just ignore it and close the installation GUI. Then kill all ansys related processes. The critical thing should be the ownership of the directory $HOME/.ansys. The installation is by sudo or root while the execution is by a regular user. That is the problem. At least for me, this solution works.
>
I tried to install it again and just shut down the installation when it hangs by killing all ansys related processes. I install using `sudo` but always run by the regular way. Neither workbench nor Fluent start for me. Do you do any additional settings before or after the installation ?

**Comment by jingchangshi** [comment]
I installed it in a fresh Ubuntu 18.04. I've no idea what is happening on your side. I just provide my experiences. Hope it helps you.

**Comment by IshaanDesai** [comment]
Due to persistent issues with ANSYS working on Ubuntu 16.04 system, FLUENT 2019 R3 was done on CentOS 7 and as it is a supported OS the installation happens seamlessly.

**Comment by IshaanDesai** [comment]
ANSYS Fluent 2019 R3 v19.5 works on Ubuntu 18.04 system. The installation stalls at ~90% but can be closed directly. ANSYS Workbench and Fluent can be run directly by launching the respective executables. Installation procedure is followed as given on [this forum](https://www.cfd-online.com/Forums/ansys/199190-ansys-18-2-ubuntu-16-04-installation-guide.html)
